"""
Shifu export formats — Markdown, HTML, and more.

Depends on the JSON export data structure from shifu_import_export_funcs.
"""

import re
import html as html_mod
from datetime import datetime
from typing import Any


def _parse_outline_tree(items: list[dict], structure: dict) -> list[dict]:
    """Attach outline items to their positions in the tree structure."""
    item_map = {i["outline_item_bid"]: i for i in items}
    enriched = []

    def walk(node: dict, depth: int):
        if node.get("type") == "outline":
            bid = node.get("id", "")
            item = item_map.get(bid)
            if item and not item.get("hidden"):
                enriched.append({**item, "_depth": depth})
        for child in node.get("children", []):
            walk(child, depth + 1)

    for root in structure.get("children", []):
        walk(root, 1)

    return enriched


def _mdflow_to_text(content: str) -> str:
    """Strip MDFlow markers but keep text, images, links."""
    if not content:
        return ""
    # Remove MDFlow section markers
    text = re.sub(r"^===\s*#+?\s*", "### ", content, flags=re.MULTILINE)
    text = re.sub(r"^===\s*", "", text, flags=re.MULTILINE)
    # Remove HTML comments
    text = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)
    return text.strip()


def _render_mdflow_to_html(content: str) -> str:
    """Convert MDFlow content to HTML."""
    if not content:
        return ""
    html_parts = []
    lines = content.split("\n")
    in_section = False

    for line in lines:
        stripped = line.strip()
        # Section marker: === # Title
        m = re.match(r"^===\s*#+\s*(.+)$", stripped)
        if m:
            if in_section:
                html_parts.append("</div>")
            html_parts.append(f'<div class="mdf-section">')
            html_parts.append(f"<h3>{html_mod.escape(m.group(1))}</h3>")
            in_section = True
            continue
        if stripped == "---":
            continue
        # Images: ![alt](url)
        img_match = re.match(r"^!\[(.*?)\]\((.*?)\)$", stripped)
        if img_match:
            html_parts.append(
                f'<figure><img src="{html_mod.escape(img_match.group(2))}" '
                f'alt="{html_mod.escape(img_match.group(1))}" '
                f'style="max-width:100%;height:auto;border-radius:8px;" />'
                f"</figure>"
            )
            continue
        # Videos: detected by URL extensions
        video_match = re.search(
            r'\((https?://[^)]+\.(mp4|m3u8|webm)[^)]*)\)', stripped
        )
        if video_match:
            url = video_match.group(1)
            html_parts.append(
                f'<video controls style="max-width:100%;border-radius:8px;">'
                f'<source src="{html_mod.escape(url)}">'
                f"</video>"
            )
            continue
        # Regular paragraphs
        if stripped:
            html_parts.append(f"<p>{html_mod.escape(stripped)}</p>")
        else:
            html_parts.append("<br/>")

    if in_section:
        html_parts.append("</div>")
    return "\n".join(html_parts)


def _detect_video_urls(text: str) -> str:
    """Convert video URLs in text to markdown/HTML friendly format."""
    return text


# ── Markdown export ──

def export_to_markdown(export_data: dict) -> str:
    """Export shifu as a Markdown document."""
    shifu = export_data.get("shifu", {})
    items = _parse_outline_tree(
        export_data.get("outline_items", []),
        export_data.get("structure", {}),
    )

    md = []
    md.append(f"# {shifu.get('title', 'Untitled')}\n")
    if shifu.get("description"):
        md.append(f"> {shifu.get('description')}\n")
    md.append(f"")
    md.append(f"_Exported at: {export_data.get('exported_at', '')}_\n")
    md.append("---\n")

    for item in items:
        depth = item.get("_depth", 1)
        prefix = "#" * min(depth + 1, 6)
        md.append(f"\n{prefix} {item.get('title', '')}\n")
        content = _mdflow_to_text(item.get("content", ""))
        if content:
            md.append(f"{content}\n")

    md.append("\n---\n")
    md.append(f"_Generated by AI-Shifu v{export_data.get('version', '1.0')}_\n")
    return "\n".join(md)


# ── HTML export ──

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans SC", sans-serif;
    max-width: 860px; margin: 0 auto; padding: 2em 1.5em;
    color: #1a1a2e; line-height: 1.8; background: #fafafa;
  }}
  h1 {{ font-size: 2em; margin-bottom: 0.5em; color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 0.3em; }}
  h2 {{ font-size: 1.5em; margin: 1.5em 0 0.5em; color: #0f3460; }}
  h3 {{ font-size: 1.2em; margin: 1.2em 0 0.4em; color: #533483; }}
  h4 {{ font-size: 1.1em; margin: 1em 0 0.3em; }}
  p {{ margin: 0.6em 0; }}
  .meta {{ color: #888; font-size: 0.9em; margin-bottom: 1.5em; }}
  .mdf-section {{ background: #fff; border-radius: 8px; padding: 1em 1.5em; margin: 1em 0; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
  figure {{ margin: 1em 0; text-align: center; }}
  img {{ max-width: 100%; height: auto; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }}
  video {{ max-width: 100%; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }}
  blockquote {{ border-left: 4px solid #0f3460; padding-left: 1em; margin: 1em 0; color: #555; background: #f0f0f5; border-radius: 0 8px 8px 0; padding: 0.8em 1em; }}
  code {{ background: #e8e8ee; padding: 0.2em 0.4em; border-radius: 4px; font-size: 0.9em; }}
  pre {{ background: #1a1a2e; color: #f0f0f5; padding: 1em; border-radius: 8px; overflow-x: auto; }}
  hr {{ border: none; border-top: 1px solid #ddd; margin: 2em 0; }}
  .footer {{ text-align: center; color: #aaa; font-size: 0.8em; margin-top: 3em; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #1a1a2e; color: #e0e0e0; }}
    .mdf-section {{ background: #16213e; }}
    blockquote {{ background: #0f3460; color: #ccc; }}
    code {{ background: #0f3460; }}
    h1 {{ color: #e94560; border-bottom-color: #e94560; }}
    h2 {{ color: #e94560; }}
    h3 {{ color: #ffa500; }}
    .meta {{ color: #888; }}
  }}
</style>
</head>
<body>
{body}
<div class="footer">
  <p>Generated by AI-Shifu | {exported_at}</p>
</div>
</body>
</html>"""


def export_to_html(export_data: dict) -> str:
    """Export shifu as a standalone HTML document."""
    shifu = export_data.get("shifu", {})
    items = _parse_outline_tree(
        export_data.get("outline_items", []),
        export_data.get("structure", {}),
    )

    body_parts = []
    body_parts.append(f'<h1>{html_mod.escape(shifu.get("title", "Untitled"))}</h1>')
    if shifu.get("description"):
        body_parts.append(
            f'<blockquote>{html_mod.escape(shifu.get("description", ""))}</blockquote>'
        )
    body_parts.append(
        f'<p class="meta">📅 {export_data.get("exported_at", "")}</p>'
    )
    body_parts.append("<hr/>")

    for item in items:
        depth = item.get("_depth", 1)
        tag = f"h{min(depth + 1, 6)}"
        body_parts.append(
            f'<{tag} id="{html_mod.escape(item.get("outline_item_bid", ""))}">'
            f'{html_mod.escape(item.get("title", ""))}'
            f"</{tag}>"
        )
        content = _render_mdflow_to_html(item.get("content", ""))
        if content:
            body_parts.append(content)

    return HTML_TEMPLATE.format(
        title=html_mod.escape(shifu.get("title", "Untitled")),
        body="\n".join(body_parts),
        exported_at=export_data.get("exported_at", ""),
    )
